site_name: Lizard
site_url: https://lizard.dev/
nav:
  - About: index.md
  - getting_started.md
  - language.md
  - examples.md
  - module_reference.md
  - machine_safety.md
  - tools.md
repo_url: https://github.com/zauberzeug/lizard
edit_uri: edit/main/docs/
theme:
  name: material
  font:
    text: Source Sans Pro
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - def_list
  - mdx_include:
      base_path: docs
